# .goreleaser.yml
# Build customization
builds:
  - main: waflyctl.go
    binary: waflyctl
    goos:
      - windows
      - darwin
      - linux
    goarch:
      - amd64
# Archive customization
archive:
  format: tar.gz
  files:
    - waflyctl.toml
    - config_examples/waflyctl.toml.example
    - README.md
# HomeBrew Tap generation
brew:
  github:
    owner: fastly
    name: homebrew-tap
  folder: Formula
  homepage:  https://github.com/fastly/waflyctl
  description: Allows you to provision a Fastly waf object with pre-determine rules, OWASP config, response, and logging endpoints. Also manage rules, and their status.
  custom_block: |
    head do
      url "https://github.com/fastly/waflyctl.git"
      depends_on "dep" => :build
      depends_on "go" => :build
    end
  install: |
    def install
      if build.head?
        ENV["GOPATH"] = buildpath
        (buildpath/"src/github.com/fastly/waflyctl").install buildpath.children
        cd "src/github.com/fastly/waflyctl" do
          system "dep", "ensure", "-vendor-only"
          system "go", "build", "-o", buildpath/"waflyctl"
        end
      end

      bin.install "waflyctl"
    end
  test: |
    system "#{bin}/waflyctl"
